### ISSUE TITLE
Load Phoenix query servers under more modes?

### ISSUE THREAD

**Issue by chu11** [chu11/magpie#100]
@bpanneton I noticed this in magpie-run

    if [ ${PHOENIX_MODE} == "server" ]
    then
        # Make variables unspecified for launching
        Magpie_make_all_local_dirs_unspecified

        echo "Starting Phoenix Queryserver"
        ${MAGPIE_SCRIPTS_HOME}/bin/magpie-phoenix.sh start

This doesn't seem right to me.  Why would phoenix query servers only be launched with PHOENIX_MODE == server?  Wouldn't we want them started with "script" or "interactive" as well?

I think perhaps it's meant for PHOENIX_MODE != "performanceeval"?

Or perhaps we should include a "setuponly" option for Phoenix, just for consistency to other tools.

**Comment by bpanneton** [comment]
So Phoenix is an oddball. It can run a server (similar to thrift) or be run with the jar. It is really like a shim over HBase. For instance, you can run a mapreduce job that calls into phoenix to write to hbase. This would not use the server from my understanding. Also the performanceeval does not use the server.

**Comment by chu11** [comment]
It makes sense to me that performanceeval doesn't need it, but what if someone wanted to run a script that uses the server?

Perhaps there should be an alternate variable instead like PHOENIX_START_QUERYSERVER indicating that the server should be started?

**Comment by bpanneton** [comment]
I guess they could do that, but I feel like they would be going out of their way to do that. If they are running a script they would likely want to run it with bin/sqlline.py <script>. I think that is how I set it up at least. If you are using the server I think it would only make sense to have something else feed phoenix, like spark. Even then, you might not need the server as spark can use the spark-phoenix jar and write directly. Regardless, you would probably be running a spark script. At least that is how I have been using it.

**Comment by chu11** [comment]
Ahhh, ok, that's a subtlety I didn't get.  That using the server is predominantly through Spark or some other type of thing.   We can leave for now.  This thread of communication atleast documents this subtlety.
