### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by mmrezaie** [chu11/magpie#19]
Hi,

Since I cannot find how to ask this question anywhere else, I will do it here. Feel free to delete it if this is not the right place for it.

I am looking into the code and there is no documentation to show how should users use magpie. I do it like this: In script-templates folder I use the Makefile for my cluster customizations. Then with magpi run I try to run sparkpi with the resulting configs. I am sure I am doing it wrong since I am changing so many of the files myself that now I ended up with scripts of my own.

Will be any documentation for running and customizing Spark, Hadoop, and Yarn. I would like to use it so that I can have it as a "module add" for other users.

Thanks

**Comment by chu11** [comment]
All the documentation is in the README file.  If there's something in there you think is missing, PLMK.
