### ISSUE TITLE
Srun error on Cray system

### ISSUE THREAD

**Issue by crystalfp** [chu11/magpie#27]
Trying to run magpie on a Cray XC40 under slurm 14.03.7
Done installation using the misc/magpie-apache-download-and-setup.sh script.
Then customized magpie.sbatch-hadoop submission script. But trying to `sbatch -k customized.sh` the job ends with the following error:

    srun: error: Unable to create job step: Requested node configuration is not available

No way making the error disappears by modifying the `#SBATCH` special comments in the script.

The wisdom here is that you should never use `srun` on Cray and instead use `aprun` because Cray version of slurm is not well integrated with their machines. Unfortunately these commands are not equivalent (changing the first `srun --no-kill -W 0` to `aprun -B` makes the first script `magpie-check-inputs` complain about missing SLURM_* variables for example).

Before trying to hack magpie scripts, I would ask:
1) Is it a known error? If yes, is there any workaround or debugging tip (besides adding -v 4 times to srun)?
2) Have you run magpie on any Cray machine?
3) On which slurm version have you tested magpie?
4) If it is not much trouble, could I have a working submission script for slurm and the log generated adding -v -v -v -v to the first srun command?

Thanks for helping!
                                       mario

-- 
Ing. Mario Valle
Swiss National Supercomputing Centre (CSCS) | http://mariovalle.name/
v. Trevano 131, 6900 Lugano, Switzerland    | Tel: +41 (91) 610.82.60

**Comment by chu11** [comment]
1) Nope, I did not know that slurm on cray machines uses aprun.  I don't have any experience with aprun so don't really know how it's different.
2) Personally no, although I can't speak of anyone else that has.
3) Slurm 2.3.3, although I would take that version w/ a grain of salt.  Our local branch differs widely with upstream.
4) I'm not sure what you mean by a working submission script?  The ones included with Magpie work.  

If 'aprun' is really that different from srun, it seems like a new job submission type would have to be added into Magpie.  If you take a look at the README, there are notes near the bottom on adding something new.  I just updated the README on Github, so if you load that one up it'll have a few more details.

LMK if you need some help at any point.

**Comment by crystalfp** [comment]
Thanks!
I just cloned the GIT repository hopefully contributing with a "crayslurmsbatch" execution mode. aprun is quite different from srun and I hope will be able to make it work.
Don't worry about question 4. Seems more clean for me to switch to aprun and stop fighting with srun.
Just a curiosity: really are you running SLURM version i2.3.3? Seems quite old, we are running 14.03.7 here.
I'll keep you informed. Thanks!
mario

**Comment by chu11** [comment]
Take the 2.3.3 w/ a grain of salt.  Slurm was developed at my company and there is a local branch.  In addition, the version numbering w/ Slurm is sort of weird.  My understanding is there has never been a 3.X to 13.X.
