### ISSUE TITLE
hbase quorum

### ISSUE THREAD

**Issue by bpanneton** [chu11/magpie#34]
Is there a variable that sets the hbasezookeeperquorum? When I run interactively, even when I set the conf dir for hbase, this doesn't seem to get set internally. I must set it manually like such:

conf = {"hbase.zookeeper.quorum": host, <----------------- list of nodes
            "hbase.mapred.outputtable": table,
            "mapreduce.outputformat.class": "org.apache.hadoop.hbase.mapreduce.TableOutputFormat",
            "mapreduce.job.output.key.class": "org.apache.hadoop.hbase.io.ImmutableBytesWritable",
            "mapreduce.job.output.value.class": "org.apache.hadoop.io.Writable"}

I was hoping I didn't need to set anything, because it requires a lookup.

I tried setting the classpath with  --driver-class-path and at first thought it was working. However it does not seem to be the case.

**Comment by chu11** [comment]
could you try adding HBASE_CONF_DIR to SPARK_CLASSPATH?

**Comment by bpanneton** [comment]
I had to add the HBASE_CONF_DIR/hbase-site.xml file rather than the directory. I added it directly to my spark-submit using the flag --driver-class-path

**Comment by bpanneton** [comment]
Didn't mean to close and I was wrong abou the hbase-site.xml. Checking the logs, it attempts to use localhost.

**Comment by chu11** [comment]
So no indication of what made it work for you?

**Comment by bpanneton** [comment]
The only way I can get it to work is by setting the config with the following:

    conf = {"hbase.zookeeper.quorum": hosts}

where hosts is a comma separated list of the quorum.

**Comment by chu11** [comment]
Believe #75 solves this need.
