### ISSUE TITLE
MAGPIE_PRE_JOB_RUN environment

### ISSUE THREAD

**Issue by bpanneton** [chu11/magpie#44]
What would be the best way to source the PRE_JOB_RUN script? It appears it runs within its own environment from the magpie-pre-run. For instance, in my pre run I need to source a few scripts which setup my environment including mpi.

I would like to just change that line to source ${MAGPIE_PRE_JOB_RUN} but I feel like that is not the best way to do this.

**Comment by chu11** [comment]
Would the new LOCAL_REQUIREMENTS config work for you?  See the script-tamplates/Makefile for info.

**Comment by bpanneton** [comment]
Yes, that will work. I've been working on the localonnetworkdrive since I can't use master at the moment. It currently doesn't have LOCAL_REQUIREMENTS yet. How soon will you be merging master with localonnetworkdrive?

**Comment by chu11** [comment]
I'll do a release then merge.

**Comment by chu11** [comment]
it's now in master

**Comment by bpanneton** [comment]
Awesome! Thanks! Once I get switched over and running I'll send you the up to date lsf patch.
