### ISSUE TITLE
Support newer versions of software

### ISSUE THREAD

**Issue by chu11** [chu11/magpie#58]

**Comment by chu11** [comment]
Spark 1.4
Hadoop 2.7.X
storm 0.9.5
hbase 0.98.13 (or 1.0 line )
pig 0.15

depends on the java they are built for

**Comment by chu11** [comment]
Atleast Hadoop 2.7 & hbase require never java's then my systems.  So may not be able to support until later.

**Comment by bpanneton** [comment]
Which version of java? I can test jdk1.8.0_51 and jdk1.8.0_60

**Comment by chu11** [comment]
it appears hadoop & hbase require 1.7.  My cluster's defaults are 1.6.  Of course not impossible, I have to go download a new jvm and deal with it.  Just gonna take time.

Also, I have to maintain the "no-local-dirs" patches now, so takes a bit more time.  Hadoop patches seemed to merge in cleanly, but I'm playing w/ spark and those patches are not clean.  Spark did a bunch of changes uptream.  Ugh ....

**Comment by bpanneton** [comment]
Let me know if I can help

**Comment by chu11** [comment]
If you'd like to try and add Hadoop 2.7 support that'd be great if you have the 1.7 JVM already running around.  From my initial trial, it seems the Hadoop 2.6 patches apply relatively cleanly.

**Comment by chu11** [comment]
Spark 1.4.1 supported in upstream now

**Comment by chu11** [comment]
Storm 0.9.5 in master now

**Comment by chu11** [comment]
Gonna make a new ticket to deal w/ new versions that need java 1.7
