### ISSUE TITLE
Teardown Script

### ISSUE THREAD

**Issue by bpanneton** [chu11/magpie#70]
I think it would be nice to move all the teardown  stuff to a file like magpie-teardown. Then this would allow one to quickly and safely shutdown the cluster while in interactive mode. I'm not sure on all the logistics of how to get all the variables automatically but I think it wouldn't be too difficult.

I wanted to run it by you and see if you had any thoughts on it before I attempted to do it.

**Comment by bpanneton** [comment]
Actually it might be simpler to put a trap and just interrupt the sleep.

**Comment by chu11** [comment]
That sounds like a great idea.  Hypothetically there could be two scripts, like

magpie-interactive-setup.sh <your env file>
magpie-interactive-teardown.sh <your env file>

where the env file points to whatever you setup for MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT.

Or perhaps MAGPIE_ENVIRONMENT_VARIABLE_SCRIPT should be automatically generated in a known location by default (user's /home??, /tmp, but would have to think about it).

**Comment by chu11** [comment]
Oh I just saw your recent pull request, the trap idea sounds good too ...

**Comment by bpanneton** [comment]
Yea the trap idea seemed like less work. I also found a bug in the hadoop shutdown. I should have a patch shortly.
