### ISSUE TITLE
generate environment variable for zookeeper nodes

### ISSUE THREAD

**Issue by chu11** [chu11/magpie#75]
likely should create new script outside of magpie-common-exports that is called only before pre-run, run, and post-run activities and after setup-core has been run.

would probably solve #34

**Comment by chu11** [comment]
also, environment variable could be used in magpie-run-phoenix-performanceeval so zookeeper node doesn't have to be parsed out of hbase-site.xml

**Comment by bpanneton** [comment]
I'm not sure if there is a way to provide the whole quorum but if there was that might be best. I just selected the first node off the list.
