### ISSUE TITLE
Hbase performance eval does not output anything when configured w/ phoenix enabled

### ISSUE THREAD

**Issue by chu11** [chu11/magpie#77]
AFAICT the performanc eval does work, it just doesn't output anything to stdout.  Maybe a log4j issue??

**Comment by chu11** [comment]
@bpanneton 

There does appear to be some jar conflicts.  In magpie-setup-hbase this change

```
 if [ "${PHOENIX_SETUP}" == "yes" ]
 then
-     hbaseclasspath=${PHOENIX_HOME}/*:${PHOENIX_HOME}/phoenix-${PHOENIX_VERSION}-client-minimal.jar:${PHOENIX_HOME}/phoenix-${PHOENIX_VERS
+     hbaseclasspath=${PHOENIX_HOME}/phoenix-${PHOENIX_VERSION}-server.jar:${hbaseclasspath}
      pre_hbasesitexml_phoenix=${hbaseconffiledir}/hbase-site-phoenix.xml
 fi
```

resolves the problem.  The original phoenix performance eval test still works.

Was there a specific need to set all those jars??

**Comment by chu11** [comment]
I can't find a reason that this is wrong, so merging upstream for now and closing this ticket.

**Comment by bpanneton** [comment]
Yea that should be fine.
