### ISSUE TITLE
Appropriately load PHOENIX_SSH_CMD in bin/magpie-phoenix.sh

### ISSUE THREAD

**Issue by chu11** [chu11/magpie#99]
It appears this will never be loaded because the phoenix env file is never loaded.

**Comment by chu11** [comment]
@bpanneton Could you look at this.

**Comment by bpanneton** [comment]
Ah, yes this is incorrect. My setup just uses ssh with kerb so the fallback to ssh doesn't cause any issues. I will fix this up after I finish the kafka commit.

**Comment by chu11** [comment]
Fixed with merge #102
